### ISSUE TITLE
Fragments requires nim version 0.19.9 that doesn't exist

### ISSUE THREAD

**Issue by lolgab** [sinkingsugar/fragments#2]
I don't know what is the real minimum required version (if 0.19.0 or 0.19.2) but maybe a typo made it 0.19.9.

**Comment by lolgab** [comment]
I saw right now that it points to a custom (maybe dev) version of nim present in your conda channel. It will be installed if you use your conda method.

**Comment by lolgab** [comment]
I noted that with default setup it doesn't find the `ATen/ATen.h` include file.
I had to link the /lib/include content to /include dir to let the linker see it.
```bash
ln -s $ATEN/lib/include/** $ATEN/include
```
You should add `$ATEN/lib/include/` to the include PATH

**Comment by sinkingsugar** [comment]
0.19.9 is the development version also on the main nim repository.
Probably nimble is not picking it either tho. Thanks for pointing it out! We will check.

**Comment by sinkingsugar** [comment]
> I noted that with default setup it doesn't find the `ATen/ATen.h` include file.
> I had to link the /lib/include content to /include dir to let the linker see it.
> 
> ```shell
> ln -s $ATEN/lib/include/** $ATEN/include
> ```
> 
> You should add `$ATEN/lib/include/` to the include PATH

Did you fetch nimtorch from conda recently?
Should be fine as it is here defined fine:
https://github.com/fragcolor-xyz/nimtorch/blob/451769c517c4384fc7929d5d723942049acdc6b1/torch/torch_cpp.nim#L64

**Comment by lolgab** [comment]
Nice, probably I messed up with installation because at start I wanted to install it from nimble. Thank you.

**Comment by sinkingsugar** [comment]
Makes sense actually! I did not tag a new version of nimtorch in a while :) Fixed both hopefully now! Thanks for your report.
